# Generated by Django 5.1.5 on 2025-02-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveMapPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_name', models.CharField(max_length=50, unique=True, verbose_name='Map Name')),
                ('map_image', models.ImageField(upload_to='media/maps/map_image', verbose_name='Map Image')),
                ('map_logo', models.ImageField(upload_to='media/maps/map_logo', verbose_name='Map Logo Image')),
            ],
            options={
                'verbose_name': 'Active Map Pool',
                'verbose_name_plural': 'Active Map Pool',
            },
        ),
    ]
