# Generated by Django 5.1.5 on 2025-02-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs2grenades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveMapPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_name', models.CharField(max_length=50, unique=True, verbose_name='Map Name')),
                ('map_image', models.ImageField(upload_to='reserve_pool_maps/map_image', verbose_name='Map Image')),
                ('map_logo', models.ImageField(upload_to='reserve_pool_maps/map_logo', verbose_name='Map Logo Image')),
            ],
            options={
                'verbose_name': 'Reserve Map Pool',
                'verbose_name_plural': 'Reserve Map Pool',
            },
        ),
        migrations.AlterModelOptions(
            name='activemappool',
            options={'verbose_name': 'Reserve Map Pool', 'verbose_name_plural': 'Reserve Map Pool'},
        ),
        migrations.AlterField(
            model_name='activemappool',
            name='map_image',
            field=models.ImageField(upload_to='maps/map_image', verbose_name='Map Image'),
        ),
        migrations.AlterField(
            model_name='activemappool',
            name='map_logo',
            field=models.ImageField(upload_to='maps/map_logo', verbose_name='Map Logo Image'),
        ),
    ]
