# Generated by Django 5.1.5 on 2025-02-13 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs2grenades', '0002_reservemappool_alter_activemappool_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activemappool',
            options={'verbose_name': 'Active Map Pool', 'verbose_name_plural': 'Active Map Pool'},
        ),
    ]
