# Generated by Django 5.1.5 on 2025-02-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs2grenades', '0003_alter_activemappool_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, verbose_name='Tag Name')),
                ('help_text', models.TextField(editable=False, help_text='You can add these tags to the posts')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': '\u200b\u200b\u200b\u200b Tags',
            },
        ),
        migrations.AlterModelOptions(
            name='activemappool',
            options={'verbose_name': 'Active Map Pool', 'verbose_name_plural': '\u200b Active Map Pool'},
        ),
        migrations.AlterModelOptions(
            name='reservemappool',
            options={'verbose_name': 'Reserve Map Pool', 'verbose_name_plural': '\u200b\u200b Reserve Map Pool'},
        ),
        migrations.CreateModel(
            name='GuidePosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(max_length=112)),
                ('banner', models.ImageField(upload_to='guide_banners/')),
                ('content', models.TextField()),
                ('public', models.BooleanField(default=True, help_text='If marked the post will be public')),
                ('slug', models.SlugField(editable=False, help_text='Auto-populated, this will be the URL for the post', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Auto-populated')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Auto-populated')),
                ('tags', models.ManyToManyField(blank=True, help_text='This will help search engine', to='cs2grenades.tags')),
            ],
            options={
                'verbose_name': 'Grenade Guide Post',
                'verbose_name_plural': '\u200b\u200b\u200b Grenades Guide Posts',
            },
        ),
    ]
