# Generated by Django 5.1.5 on 2025-02-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs2grenades', '0006_alter_tags_tag_name_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guideposts',
            options={'verbose_name': 'Guide Post', 'verbose_name_plural': 'Guide Posts'},
        ),
        migrations.CreateModel(
            name='TutorialPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_title', models.CharField(max_length=32, unique=True)),
                ('tutorial_description', models.CharField(max_length=112)),
                ('tutorial_banner', models.ImageField(upload_to='tutorial_banners/')),
                ('tutorial_video', models.URLField()),
                ('public', models.BooleanField(default=True, help_text='If marked the post will be public')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Auto-populated')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Auto-populated')),
                ('tags', models.ManyToManyField(blank=True, help_text='This will help search engine', to='cs2grenades.tags')),
            ],
            options={
                'verbose_name': 'Tutorial Post',
                'verbose_name_plural': 'Tutorial Posts',
            },
        ),
    ]
