# Generated by Django 5.1.5 on 2025-03-03 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs2grenades', '0008_favorite_tutorial_alter_tutorialposts_tutorial_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='tutorial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='cs2grenades.tutorialposts'),
        ),
    ]
