# Generated by Django 5.1.5 on 2025-03-03 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs2grenades', '0009_alter_favorite_tutorial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='tutorial',
        ),
    ]
