# Generated by Django 5.1.5 on 2025-03-03 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs2grenades', '0010_remove_favorite_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='tutorial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='cs2grenades.tutorialposts'),
        ),
    ]
