# Generated by Django 5.1.5 on 2025-03-04 00:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs2grenades', '0011_favorite_tutorial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'guide', 'tutorial')},
        ),
    ]
