# Generated by Django 5.1.5 on 2025-03-11 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs2grenades', '0017_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='avatar',
            new_name='image',
        ),
    ]
