# Generated by Django 5.1.5 on 2025-03-11 19:38

import cs2grenades.utils.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_alter_sitesettings_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/%Y/%m', validators=[cs2grenades.utils.images.validate_image_size]),
        ),
    ]
